package com.nico.test;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class MeterData {

    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.meter_id
     *
     * @mbg.generated
     */
    private String meterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.create_time
     *
     * @mbg.generated
     */
    private String createTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxygzdn
     *
     * @mbg.generated
     */
    private String zxygzdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxygfl1dn
     *
     * @mbg.generated
     */
    private String zxygfl1dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxygfl2dn
     *
     * @mbg.generated
     */
    private String zxygfl2dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxygfl3dn
     *
     * @mbg.generated
     */
    private String zxygfl3dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxygfl4dn
     *
     * @mbg.generated
     */
    private String zxygfl4dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxwgzdn
     *
     * @mbg.generated
     */
    private String zxwgzdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxwgfl1dn
     *
     * @mbg.generated
     */
    private String zxwgfl1dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxwgfl2dn
     *
     * @mbg.generated
     */
    private String zxwgfl2dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxwgfl3dn
     *
     * @mbg.generated
     */
    private String zxwgfl3dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zxwgfl4dn
     *
     * @mbg.generated
     */
    private String zxwgfl4dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxygzdn
     *
     * @mbg.generated
     */
    private String fxygzdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxygfl1dn
     *
     * @mbg.generated
     */
    private String fxygfl1dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxygfl2dn
     *
     * @mbg.generated
     */
    private String fxygfl2dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxygfl3dn
     *
     * @mbg.generated
     */
    private String fxygfl3dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxygfl4dn
     *
     * @mbg.generated
     */
    private String fxygfl4dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxwgzdn
     *
     * @mbg.generated
     */
    private String fxwgzdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxwgfl1dn
     *
     * @mbg.generated
     */
    private String fxwgfl1dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxwgfl2dn
     *
     * @mbg.generated
     */
    private String fxwgfl2dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxwgfl3dn
     *
     * @mbg.generated
     */
    private String fxwgfl3dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.fxwgfl4dn
     *
     * @mbg.generated
     */
    private String fxwgfl4dn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Axdy
     *
     * @mbg.generated
     */
    private String axdy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Bxdy
     *
     * @mbg.generated
     */
    private String bxdy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Cxdy
     *
     * @mbg.generated
     */
    private String cxdy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Axdl
     *
     * @mbg.generated
     */
    private String axdl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Bxdl
     *
     * @mbg.generated
     */
    private String bxdl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Cxdl
     *
     * @mbg.generated
     */
    private String cxdl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zyggl
     *
     * @mbg.generated
     */
    private String zyggl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Axyggl
     *
     * @mbg.generated
     */
    private String axyggl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Bxyggl
     *
     * @mbg.generated
     */
    private String bxyggl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Cxyggl
     *
     * @mbg.generated
     */
    private String cxyggl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zwggl
     *
     * @mbg.generated
     */
    private String zwggl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Axwggl
     *
     * @mbg.generated
     */
    private String axwggl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Bxwggl
     *
     * @mbg.generated
     */
    private String bxwggl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Cxwggl
     *
     * @mbg.generated
     */
    private String cxwggl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zglys
     *
     * @mbg.generated
     */
    private String zglys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Axgglys
     *
     * @mbg.generated
     */
    private String axgglys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Bxgglys
     *
     * @mbg.generated
     */
    private String bxgglys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Cxgglys
     *
     * @mbg.generated
     */
    private String cxgglys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.zszgl
     *
     * @mbg.generated
     */
    private String zszgl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Axszgl
     *
     * @mbg.generated
     */
    private String axszgl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Bxszgl
     *
     * @mbg.generated
     */
    private String bxszgl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meter_data.Cxszgl
     *
     * @mbg.generated
     */
    private String cxszgl;


}